name: flutter_clerk_sdk
description: Flutter SDK for Clerk authentication using REST API calls
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  crypto: ^3.0.3
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true